<div class="el-form-grid">
    <label class="el-field el-field-full"><span class="el-field-label">Karyawan <b>*</b></span><select class="form-select el-control" name="employee_id" required><option value="">Pilih karyawan</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected((int) old('employee_id', $employeeLoan->employee_id ?? 0) === $employee->id)>{{ $employee->code }} · {{ $employee->name }}</option>@endforeach</select></label>
    <label class="el-field"><span class="el-field-label">Tanggal pencairan <b>*</b></span><input class="form-control el-control" type="date" name="date" value="{{ old('date', optional($employeeLoan->date ?? null)->toDateString() ?: now()->toDateString()) }}" required></label>
    <label class="el-field"><span class="el-field-label">Nominal pinjaman <b>*</b></span><span class="el-money"><span>Rp</span><input class="form-control el-control" type="number" name="principal_amount" min="0.01" step="0.01" inputmode="decimal" value="{{ old('principal_amount', $employeeLoan->principal_amount ?? '') }}" placeholder="0" required></span></label>
    <label class="el-field"><span class="el-field-label">Jatuh tempo <em>opsional</em></span><input class="form-control el-control" type="date" name="due_date" value="{{ old('due_date', optional($employeeLoan->due_date ?? null)->toDateString()) }}"></label>
    <label class="el-field"><span class="el-field-label">Nominal angsuran <em>opsional</em></span><span class="el-money"><span>Rp</span><input class="form-control el-control" type="number" name="installment_amount" min="0.01" step="0.01" inputmode="decimal" value="{{ old('installment_amount', $employeeLoan->installment_amount ?? '') }}" placeholder="0"></span></label>
    <label class="el-field"><span class="el-field-label">Jumlah angsuran <em>opsional</em></span><input class="form-control el-control" type="number" name="installment_count" min="1" step="1" inputmode="numeric" value="{{ old('installment_count', $employeeLoan->installment_count ?? '') }}"></label>
    <label class="el-field"><span class="el-field-label">Dicairkan dari <b>*</b></span><select class="form-select el-control" name="cash_account_id" required><option value="">Pilih kas / bank</option>@foreach($cashAccounts as $account)<option value="{{ $account->id }}" @selected((int) old('cash_account_id', $employeeLoan->cash_account_id ?? 0) === $account->id)>{{ $account->code }} · {{ $account->name }}</option>@endforeach</select></label>
    <label class="el-field"><span class="el-field-label">Akun piutang <b>*</b></span><select class="form-select el-control" name="receivable_account_id" required><option value="">Pilih akun piutang</option>@foreach($receivableAccounts as $account)<option value="{{ $account->id }}" @selected((int) old('receivable_account_id', $employeeLoan->receivable_account_id ?? ($receivableAccounts->firstWhere('code', '1307')?->id)) === $account->id)>{{ $account->code }} · {{ $account->name }}</option>@endforeach</select></label>
    <label class="el-field"><span class="el-field-label">No. referensi <em>opsional</em></span><input class="form-control el-control" type="text" name="reference" maxlength="100" value="{{ old('reference', $employeeLoan->reference ?? '') }}"></label>
    <label class="el-field"><span class="el-field-label">Keterangan <em>opsional</em></span><input class="form-control el-control" type="text" name="description" maxlength="255" value="{{ old('description', $employeeLoan->description ?? 'Pinjaman karyawan') }}"></label>
    <label class="el-field el-field-full"><span class="el-field-label">Catatan <em>opsional</em></span><textarea class="form-control el-control" name="notes" rows="3">{{ old('notes', $employeeLoan->notes ?? '') }}</textarea></label>
</div>

@if($errors->any())<div class="alert alert-danger mt-3 mb-0"><strong>Periksa kembali data yang diisi.</strong><ul class="mb-0 mt-1">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
