@extends('layouts.app')
@section('title', 'Accounting • Detail Pinjaman Karyawan')
@php $fmt=fn($n)=>number_format((float)$n,0,',','.'); $paid=(float)$employeeLoan->repayments->where('status','posted')->sum('amount'); $remaining=max(0,(float)$employeeLoan->principal_amount-$paid); $labels=['draft'=>'Draft','posted'=>'Posted','settled'=>'Lunas','void'=>'Void']; @endphp
@push('head')
    @include('production.dashboard.partials._gf-styles')
    <style>.el-detail{display:grid;gap:1rem}.el-actions{display:flex;justify-content:flex-end;gap:.5rem;flex-wrap:wrap}.el-btn{display:inline-flex;align-items:center;min-height:40px;padding:.55rem .95rem;border:1px solid #dbe3ee;border-radius:999px;background:#fff;color:#0f172a;text-decoration:none;font-size:.82rem;font-weight:850}.el-btn-primary{color:#fff;background:#0f172a;border-color:#0f172a}.el-btn-danger{color:#991b1b;background:#fff5f5;border-color:#fecaca}.el-status{display:inline-flex;border-radius:999px;padding:.22rem .6rem;font-size:.72rem;font-weight:850}.el-status-draft{color:#92400e;background:#fef3c7}.el-status-posted{color:#166534;background:#dcfce7}.el-status-settled{color:#075985;background:#e0f2fe}.el-status-void{color:#991b1b;background:#fee2e2}.el-info{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.75rem}.el-card{border:1px solid #e2e8f0;border-radius:14px;background:#fff;padding:.85rem}.el-label{color:#64748b;font-size:.7rem;font-weight:900;text-transform:uppercase}.el-value{margin-top:.2rem;color:#0f172a;font-weight:900}.el-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.7rem}.el-field{display:grid;gap:.3rem}.el-field-full{grid-column:1/-1}.el-field span{color:#64748b;font-size:.72rem;font-weight:900;text-transform:uppercase}.el-control{min-height:40px;border-radius:11px;border-color:#dbe3ee;box-shadow:none}.el-table th{color:#64748b;font-size:.7rem;text-transform:uppercase;white-space:nowrap}@media(max-width:800px){.el-info{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.el-form-grid{grid-template-columns:1fr}.el-field-full{grid-column:auto}.el-actions .el-btn{flex:1;justify-content:center}}</style>
@endpush
@section('content')
<x-gf.page eyebrow="Accounting" title="Detail Pinjaman Karyawan" description="{{ $employeeLoan->employee?->code }} · {{ $employeeLoan->employee?->name }}">
    <x-slot:actions><div class="el-actions"><a class="el-btn" href="{{ route('accounting.employee-loans.index') }}">Daftar</a>@if($employeeLoan->status==='draft')<a class="el-btn" href="{{ route('accounting.employee-loans.edit',$employeeLoan) }}">Edit</a><form method="POST" action="{{ route('accounting.employee-loans.post',$employeeLoan) }}">@csrf<button class="el-btn el-btn-primary" type="submit">Post Pinjaman</button></form><form method="POST" action="{{ route('accounting.employee-loans.destroy',$employeeLoan) }}" onsubmit="return confirm('Hapus draft pinjaman ini?')">@csrf @method('DELETE')<button class="el-btn el-btn-danger" type="submit">Hapus</button></form>@endif @if($employeeLoan->status==='posted')<form method="POST" action="{{ route('accounting.employee-loans.void',$employeeLoan) }}" onsubmit="return confirm('Void pinjaman ini?')">@csrf<input type="hidden" name="reason" value="Void dari detail"><button class="el-btn el-btn-danger" type="submit">Void</button></form>@endif</div></x-slot:actions>
    <div class="el-detail">
        @if(session('message'))<div class="alert alert-{{ session('status') === 'error' ? 'danger' : 'success' }} mb-0">{{ session('message') }}</div>@endif
        <div class="el-info"><div class="el-card"><div class="el-label">Status</div><div class="el-value"><span class="el-status el-status-{{ $employeeLoan->status }}">{{ $labels[$employeeLoan->status] ?? $employeeLoan->status }}</span></div></div><div class="el-card"><div class="el-label">Nominal Pinjaman</div><div class="el-value">Rp {{ $fmt($employeeLoan->principal_amount) }}</div></div><div class="el-card"><div class="el-label">Sudah Dibayar</div><div class="el-value">Rp {{ $fmt($paid) }}</div></div><div class="el-card"><div class="el-label">Sisa Piutang</div><div class="el-value">Rp {{ $fmt($remaining) }}</div></div></div>
        <x-gf.panel title="Ringkasan" subtitle="{{ optional($employeeLoan->date)->format('d/m/Y') }}{{ $employeeLoan->reference ? ' · '.$employeeLoan->reference : '' }}"><div class="table-responsive"><table class="table mb-0"><tbody><tr><th>Karyawan</th><td>{{ $employeeLoan->employee?->code }} · {{ $employeeLoan->employee?->name }}</td></tr><tr><th>Jatuh tempo</th><td>{{ optional($employeeLoan->due_date)->format('d/m/Y') ?: '—' }}</td></tr><tr><th>Rencana angsuran</th><td>{{ $employeeLoan->installment_amount ? 'Rp '.$fmt($employeeLoan->installment_amount) : '—' }}{{ $employeeLoan->installment_count ? ' × '.$employeeLoan->installment_count : '' }}</td></tr><tr><th>Kas/Bank</th><td>{{ $employeeLoan->cashAccount?->code }} · {{ $employeeLoan->cashAccount?->name }}</td></tr><tr><th>Akun piutang</th><td>{{ $employeeLoan->receivableAccount?->code }} · {{ $employeeLoan->receivableAccount?->name }}</td></tr><tr><th>Jurnal</th><td>@if($employeeLoan->journal)<a href="{{ route('accounting.journals.show',$employeeLoan->journal) }}">#{{ $employeeLoan->journal_id }}</a>@else Belum dibuat @endif</td></tr>@if($employeeLoan->notes)<tr><th>Catatan</th><td>{{ $employeeLoan->notes }}</td></tr>@endif</tbody></table></div></x-gf.panel>
        @if(in_array($employeeLoan->status,['posted','settled'],true) && $remaining>0.009)<x-gf.panel title="Catat Angsuran" subtitle="Jurnal: Debit Kas/Bank — Kredit Piutang Pinjaman Karyawan."><form method="POST" action="{{ route('accounting.employee-loans.repayments.store',$employeeLoan) }}">@csrf<div class="el-form-grid"><label class="el-field"><span>Tanggal</span><input class="form-control el-control" type="date" name="date" value="{{ now()->toDateString() }}" required></label><label class="el-field"><span>Nominal Angsuran</span><input class="form-control el-control" type="number" name="amount" min="0.01" max="{{ $remaining }}" step="0.01" required></label><label class="el-field"><span>Diterima ke</span><select class="form-select el-control" name="cash_account_id" required>@foreach($cashAccounts as $account)<option value="{{ $account->id }}">{{ $account->code }} · {{ $account->name }}</option>@endforeach</select></label><label class="el-field"><span>No. Referensi</span><input class="form-control el-control" type="text" name="reference" maxlength="100"></label><label class="el-field el-field-full"><span>Catatan</span><textarea class="form-control el-control" name="notes" rows="2"></textarea></label></div><div class="el-actions mt-3"><button class="el-btn el-btn-primary" type="submit">Simpan Angsuran Draft</button></div></form></x-gf.panel>@endif
        <x-gf.panel title="Riwayat Angsuran" subtitle="Setiap angsuran diposting terpisah agar saldo piutang tetap terlacak."><div class="table-responsive"><table class="table el-table align-middle mb-0"><thead><tr><th>Tanggal</th><th>Referensi</th><th class="text-end">Nominal</th><th>Kas/Bank</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>@forelse($employeeLoan->repayments as $repayment)<tr><td>{{ optional($repayment->date)->format('d/m/Y') }}</td><td>{{ $repayment->reference ?: '—' }}</td><td class="text-end">Rp {{ $fmt($repayment->amount) }}</td><td>{{ $repayment->cashAccount?->name }}</td><td><span class="el-status el-status-{{ $repayment->status }}">{{ $labels[$repayment->status] ?? $repayment->status }}</span></td><td class="text-end">@if($repayment->status==='draft')<form method="POST" action="{{ route('accounting.employee-loans.repayments.post',$repayment) }}" class="d-inline">@csrf<button class="el-btn el-btn-primary" type="submit">Post</button></form>@elseif($repayment->status==='posted' && $repayment->source_type !== \App\Models\EmployeeLoanRepayment::SOURCE_PAYROLL_DEDUCTION)<form method="POST" action="{{ route('accounting.employee-loans.repayments.void',$repayment) }}" class="d-inline" onsubmit="return confirm('Void angsuran ini?')">@csrf<input type="hidden" name="reason" value="Void dari detail"><button class="el-btn el-btn-danger" type="submit">Void</button></form>@elseif($repayment->status==='posted')<span class="small text-muted">Dari payroll</span>@endif</td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">Belum ada angsuran.</td></tr>@endforelse</tbody></table></div></x-gf.panel>
    </div>
</x-gf.page>
@endsection
