### Test Shopee Shipping Document API Mock
POST https://promoter-quintuple-domelike.ngrok-free.dev/api/v2/logistics/get_shipping_document_data_info
Content-Type: application/json

{
    "order_sn":"231112E8YGWPXJ",
    "package_number":"OFG153490685206408",
    "recipient_address_info":[
        {
            "key":"name",
            "style":{
                "h_align":"left",
                "text_style":[
                    "bold",
                    "italic"
                ],
                "font_size":12,
                "text_color":"#000000",
                "image_width":6
            }
        }
    ]
}
