<style>
.mpcrm-card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:16px}
.mpcrm-segment-summary .mpcrm-card{min-width:0;overflow:hidden}
.mpcrm-segment-summary .mpcrm-value{overflow-wrap:anywhere;word-break:break-word}
.mpcrm-label{font-size:.68rem;font-weight:800;letter-spacing:.06em;text-transform:uppercase;color:#94a3b8}
.mpcrm-value{font-size:1.45rem;font-weight:900;color:#0f172a;line-height:1.15;margin-top:5px}
.mpcrm-sub{font-size:.72rem;color:#64748b;margin-top:5px}
.mpcrm-table th{font-size:.66rem;letter-spacing:.05em;text-transform:uppercase;color:#94a3b8;background:#f8fafc;white-space:nowrap;position:sticky;top:0;z-index:2;box-shadow:0 1px 0 #e5e7eb}
.mpcrm-table td{font-size:.8rem;vertical-align:middle}
.mpcrm-table th,.mpcrm-table td{padding:.7rem .8rem;border-bottom:1px solid #f1f5f9}
.mpcrm-prospect-row{cursor:pointer;transition:background-color .15s ease}
.mpcrm-prospect-row:hover>td,.mpcrm-prospect-row.is-expanded>td{background:#f8fafc}
.mpcrm-prospect-row:focus-visible>td{outline:2px solid #93c5fd;outline-offset:-2px}
.mpcrm-accordion-detail>td{padding:0!important;background:#f8fafc;border-bottom:1px solid #e2e8f0}
.mpcrm-order-detail{padding:1rem 1.1rem 1.05rem;border-left:3px solid #bfdbfe}
.mpcrm-order-detail-head{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem}
.mpcrm-order-detail-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.6rem;margin:1rem 0;padding:.7rem;border:1px solid #e2e8f0;border-radius:10px;background:#fff}
.mpcrm-order-detail-summary>div{display:flex;flex-direction:column;gap:.15rem}
.mpcrm-order-detail-summary span{font-size:.68rem;color:#64748b}
.mpcrm-order-detail-summary b{font-size:.78rem;color:#0f172a}
.mpcrm-order-detail-grid{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(220px,1fr);gap:1rem}
.mpcrm-order-detail-item{padding:.45rem 0;border-bottom:1px solid #e2e8f0;font-size:.76rem}
.mpcrm-order-detail-item:last-child{border-bottom:0}
@media (max-width:768px){.mpcrm-order-detail-summary,.mpcrm-order-detail-grid{grid-template-columns:1fr}.mpcrm-order-detail-head{flex-direction:column}}
.mpcrm-item-cell{width:280px;max-width:280px}
.mpcrm-item-name,.mpcrm-item-variant{display:block;max-width:250px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.mpcrm-item-name{cursor:help}
.mpcrm-wa-cell{min-width:150px}
.mpcrm-wa-status{display:inline-flex;align-items:center;border-radius:999px;padding:.2rem .5rem;font-size:.65rem;font-weight:800;white-space:nowrap}
.mpcrm-wa-status-ok{background:#dcfce7;color:#166534}.mpcrm-wa-status-failed{background:#fee2e2;color:#991b1b}.mpcrm-wa-status-pending{background:#fef3c7;color:#92400e}.mpcrm-wa-status-none{background:#f1f5f9;color:#64748b}
.mpcrm-sku-cell{width:150px;max-width:150px}
.mpcrm-sku-value{display:block;max-width:125px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.mpcrm-item-master{display:flex;align-items:center;gap:.35rem;max-width:250px;margin-top:.25rem;color:#15803d;font-size:.67rem}
.mpcrm-item-master-label{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.mpcrm-item-map-btn{border:0;background:transparent;color:#2563eb;padding:0;font-size:.65rem;font-weight:800;cursor:pointer;white-space:nowrap}
.mpcrm-item-map-btn:hover{text-decoration:underline}
.mpcrm-map-modal{position:fixed;inset:0;z-index:1050;display:none;align-items:center;justify-content:center;padding:1rem;background:rgba(15,23,42,.45)}
.mpcrm-map-modal.is-open{display:flex}
.mpcrm-map-dialog{width:min(520px,100%);background:#fff;border-radius:16px;padding:1rem 1.1rem;box-shadow:0 20px 60px rgba(15,23,42,.2)}
.mpcrm-map-head{display:flex;align-items:flex-start;justify-content:space-between;gap:.75rem;margin-bottom:.8rem}
.mpcrm-map-title{font-size:.95rem;font-weight:900;color:#0f172a}.mpcrm-map-sub{font-size:.72rem;color:#64748b;margin-top:.2rem}
.mpcrm-map-close{border:0;background:transparent;color:#64748b;font-size:1.1rem;line-height:1;cursor:pointer}
.mpcrm-map-results{display:grid;gap:.4rem;margin-top:.55rem;max-height:240px;overflow:auto}
.mpcrm-map-result{display:flex;align-items:center;justify-content:space-between;gap:.6rem;width:100%;padding:.55rem .65rem;border:1px solid #e2e8f0;border-radius:9px;background:#fff;text-align:left;cursor:pointer}
.mpcrm-map-result:hover{border-color:#93c5fd;background:#eff6ff}
.mpcrm-map-result-code{font:800 .72rem ui-monospace,SFMono-Regular,Menlo,monospace;color:#0f172a}.mpcrm-map-result-name{font-size:.72rem;color:#64748b;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.mpcrm-map-status{font-size:.74rem;color:#64748b;min-height:1.1rem;margin-top:.5rem}
.mpcrm-map-actions{display:flex;align-items:center;justify-content:space-between;gap:.6rem;border-top:1px solid #f1f5f9;margin-top:.8rem;padding-top:.8rem}
.mpcrm-sort{display:inline-flex;align-items:center;gap:.35rem;color:inherit;text-decoration:none}
.mpcrm-sort:hover,.mpcrm-sort.active{color:#2563eb}
.mpcrm-sort i{font-size:.7rem}
.mpcrm-pill{display:inline-flex;align-items:center;border-radius:999px;padding:.2rem .55rem;font-size:.67rem;font-weight:800}
.mpcrm-toolbar{background:#fff;border:1px solid #e5e7eb;border-radius:14px;padding:12px}.mpcrm-toolbar .form-label{color:#64748b;letter-spacing:.02em}.mpcrm-toolbar .form-control,.mpcrm-toolbar .form-select{border-color:#dbe3ec}.mpcrm-toolbar .form-control:focus,.mpcrm-toolbar .form-select:focus{border-color:#93c5fd;box-shadow:0 0 0 .16rem rgba(59,130,246,.1)}
.mpcrm-filter-toggle{display:flex;align-items:center;width:100%;padding:.45rem .6rem;border:1px solid #e2e8f0;border-radius:8px;background:#f8fafc;color:#334155;font-size:.72rem;font-weight:800;text-align:left;cursor:pointer}.mpcrm-filter-toggle:hover,.mpcrm-filter-toggle.is-open{border-color:#bfdbfe;background:#eff6ff;color:#1d4ed8}.mpcrm-filter-toggle-note{margin-left:.45rem;color:#94a3b8;font-size:.66rem;font-weight:600}.mpcrm-filter-toggle>i:last-child{transition:transform .15s ease}.mpcrm-filter-toggle.is-open>i:last-child{transform:rotate(180deg)}
.mpcrm-advanced-filters{padding:.65rem;border:1px solid #e2e8f0;border-radius:10px;background:#f8fafc}
.mpcrm-date-range{padding-left:2rem!important;cursor:pointer;background:#fff!important}
.mpcrm-date-icon{position:absolute;left:.7rem;top:50%;z-index:2;transform:translateY(-50%);color:#64748b;pointer-events:none;font-size:.8rem}
.mpcrm-link{text-decoration:none;color:#0f172a;font-weight:750}
.mpcrm-link:hover{color:#2563eb}
.mpcrm-chart-container{min-height:240px;margin-top:14px;padding:10px 0 0;border-top:1px solid #f1f5f9}
.mpcrm-chart-legend{display:flex;align-items:center;gap:1rem;margin-bottom:8px;font-size:.7rem;color:#64748b}
.mpcrm-chart-legend>span{display:inline-flex;align-items:center;gap:.35rem}
.mpcrm-legend-dot{display:inline-block;width:8px;height:8px;border-radius:50%}
.mpcrm-legend-revenue{background:#16a34a}.mpcrm-legend-orders{background:#2563eb}
.mpcrm-chart-grid{display:grid;grid-template-columns:repeat(var(--chart-columns),minmax(18px,1fr));align-items:end;gap:clamp(2px,.55vw,8px);height:190px;padding:4px 4px 0;background:repeating-linear-gradient(to bottom,transparent 0,transparent 45px,#e2e8f0 46px);border-bottom:1px solid #cbd5e1}
.mpcrm-chart-column{display:flex;align-items:center;justify-content:end;min-width:0;height:100%;flex-direction:column;gap:6px}
.mpcrm-chart-bars{display:flex;align-items:end;justify-content:center;gap:2px;width:100%;height:calc(100% - 18px)}
.mpcrm-chart-bar{display:block;width:calc(50% - 2px);min-width:3px;border-radius:4px 4px 0 0;transition:opacity .15s ease}
.mpcrm-chart-bar:hover{opacity:.7}.mpcrm-chart-bar-revenue{background:linear-gradient(180deg,#4ade80,#16a34a)}.mpcrm-chart-bar-orders{background:linear-gradient(180deg,#60a5fa,#2563eb)}
.mpcrm-chart-label{display:block;width:100%;overflow:hidden;color:#94a3b8;font-size:.58rem;text-align:center;text-overflow:ellipsis;white-space:nowrap}
.mpcrm-chart-shell{position:relative;margin-top:16px;padding:10px 0 0 34px;border-bottom:1px solid #cbd5e1;background:repeating-linear-gradient(to bottom,transparent 0,transparent 37px,#e2e8f0 38px)}
.mpcrm-chart-row{display:flex;align-items:end;gap:5px;height:170px;padding:0 4px}
.mpcrm-chart-column{display:flex;align-items:center;flex:1;min-width:18px;height:100%;flex-direction:column;justify-content:end;gap:5px}
.mpcrm-chart-value{font-size:.56rem;color:#64748b;white-space:nowrap;transform:rotate(-45deg);transform-origin:center bottom;height:20px}
.mpcrm-bar{width:100%;min-width:6px;max-width:34px;background:linear-gradient(180deg,#60a5fa,#2563eb);border-radius:5px 5px 0 0;opacity:.9;transition:height .2s ease,opacity .2s ease}
.mpcrm-bar:hover{opacity:1}
.mpcrm-bar-label{font-size:.58rem;color:#94a3b8;text-align:center;white-space:nowrap;overflow:hidden}
.mpcrm-chart-axis{position:absolute;left:0;top:8px;bottom:2px;display:flex;flex-direction:column;justify-content:space-between;font-size:.56rem;color:#94a3b8}
.mpcrm-executive-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}
.mpcrm-kpi-card{display:flex;align-items:center;gap:.75rem;min-height:112px;padding:15px 16px;background:#fff;border:1px solid #e5e7eb;border-radius:14px;box-shadow:0 1px 2px rgba(15,23,42,.03)}
.mpcrm-kpi-icon{display:grid;place-items:center;width:38px;height:38px;flex:0 0 38px;border-radius:11px;font-size:1rem}
.mpcrm-kpi-primary{border-top:3px solid #2563eb}.mpcrm-kpi-primary .mpcrm-kpi-icon{background:#eff6ff;color:#2563eb}
.mpcrm-kpi-success{border-top:3px solid #16a34a}.mpcrm-kpi-success .mpcrm-kpi-icon{background:#f0fdf4;color:#16a34a}
.mpcrm-kpi-purple{border-top:3px solid #7c3aed}.mpcrm-kpi-purple .mpcrm-kpi-icon{background:#f5f3ff;color:#7c3aed}
.mpcrm-kpi-whatsapp{border-top:3px solid #25d366}.mpcrm-kpi-whatsapp .mpcrm-kpi-icon{background:#ecfdf5;color:#16a34a}
.mpcrm-kpi-coverage{border-top:3px solid #0ea5e9}.mpcrm-kpi-coverage .mpcrm-kpi-icon{background:#e0f2fe;color:#0284c7}
.mpcrm-kpi-label{font-size:.66rem;font-weight:800;letter-spacing:.04em;text-transform:uppercase;color:#64748b}
.mpcrm-kpi-value{margin-top:3px;font-size:1.25rem;font-weight:900;line-height:1.15;color:#0f172a;white-space:nowrap}
.mpcrm-kpi-note{margin-top:5px;font-size:.68rem;color:#94a3b8;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.mpcrm-analytics-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));align-items:start;gap:12px}
.mpcrm-analysis-card{align-self:start;min-width:0;min-height:218px;height:auto;overflow:visible;padding:15px 16px;background:#fff;border:1px solid #e5e7eb;border-radius:14px}
.mpcrm-analysis-head{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem;padding-bottom:11px;border-bottom:1px solid #f1f5f9}
.mpcrm-analysis-head>i{display:grid;place-items:center;width:30px;height:30px;border-radius:9px;background:#f8fafc;color:#64748b;font-size:.9rem}
.mpcrm-analysis-title{margin:3px 0 0;font-size:.88rem;font-weight:850;color:#0f172a}
.mpcrm-analysis-list{display:grid;gap:11px;padding-top:14px}
.mpcrm-analysis-row-head{display:flex;align-items:center;justify-content:space-between;gap:.75rem;margin-bottom:5px;font-size:.7rem;color:#475569}.mpcrm-analysis-row-head span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.mpcrm-analysis-row-head b{padding:.16rem .42rem;border-radius:999px;background:#f1f5f9;color:#475569;font-size:.65rem;font-weight:800;white-space:nowrap}.mpcrm-analysis-row-meta{margin-top:4px;color:#94a3b8;font-size:.63rem;font-weight:650;line-height:1.1}
.mpcrm-analysis-track{height:7px;overflow:hidden;border-radius:999px;background:#eef2f7}.mpcrm-analysis-track>span{display:block;height:100%;min-width:4px;border-radius:inherit;background:linear-gradient(90deg,#60a5fa,#2563eb);transition:width .25s ease}.mpcrm-analysis-track-green{background:linear-gradient(90deg,#4ade80,#16a34a)!important}.mpcrm-analysis-track-purple{background:linear-gradient(90deg,#a78bfa,#7c3aed)!important}.mpcrm-analysis-track-orange{background:linear-gradient(90deg,#fb923c,#ea580c)!important}
.mpcrm-analysis-row-expandable{cursor:pointer;border-radius:8px;padding:3px 5px;margin:-3px -5px;transition:background .15s ease}.mpcrm-analysis-row-expandable:hover,.mpcrm-analysis-row-expandable:focus-visible{background:#f8fafc;outline:none}.mpcrm-city-toggle-icon{color:#64748b;font-size:.65rem;transition:transform .15s ease}.mpcrm-analysis-row-expandable.is-expanded .mpcrm-city-toggle-icon{transform:rotate(180deg)}.mpcrm-city-breakdown{display:grid;gap:9px;max-height:240px;overflow-y:auto;padding:10px 5px 3px;border-top:1px solid #f1f5f9}.mpcrm-analysis-row-sub{padding-left:8px}
.mpcrm-empty-analytics{padding:20px 0;text-align:center;font-size:.72rem;color:#94a3b8}
.mpcrm-orders-page{max-width:1600px;margin:0 auto}
.mpcrm-module-nav{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:.35rem;border:1px solid #e2e8f0;border-radius:13px;background:rgba(255,255,255,.82);box-shadow:0 4px 14px rgba(15,23,42,.025)}.mpcrm-nav-links{display:flex;align-items:center;gap:.25rem;flex-wrap:wrap}.mpcrm-nav-link{display:inline-flex;align-items:center;gap:.25rem;border:1px solid transparent;border-radius:9px;padding:.48rem .7rem;color:#64748b;font-size:.72rem;font-weight:750;text-decoration:none;transition:all .15s ease}.mpcrm-nav-link:hover{background:#f8fafc;color:#0f172a}.mpcrm-nav-link.is-active{border-color:#0f172a;background:#0f172a;color:#fff;box-shadow:0 2px 4px rgba(15,23,42,.12)}.mpcrm-nav-link.mpcrm-nav-import{color:#2563eb}.mpcrm-nav-link.mpcrm-nav-import:hover,.mpcrm-nav-link.mpcrm-nav-import.is-active{border-color:#2563eb;background:#eff6ff;color:#1d4ed8;box-shadow:none}.mpcrm-nav-context{display:inline-flex;align-items:center;white-space:nowrap;border-radius:999px;padding:.35rem .58rem;background:#eff6ff;color:#1d4ed8;font-size:.65rem;font-weight:850}
.mpcrm-page-header{display:flex;align-items:flex-end;justify-content:space-between;gap:1.5rem}
.mpcrm-eyebrow,.mpcrm-section-kicker{display:flex;align-items:center;gap:.45rem;color:#64748b;font-size:.66rem;font-weight:850;letter-spacing:.12em;text-transform:uppercase}
.mpcrm-eyebrow>span:not(.mpcrm-eyebrow-mark){color:#cbd5e1}.mpcrm-eyebrow-mark{width:7px;height:7px;border-radius:50%;background:#2563eb;box-shadow:0 0 0 4px #dbeafe}
.mpcrm-page-title{margin:.55rem 0 0;color:#0f172a;font-size:clamp(1.55rem,2.4vw,2.25rem);font-weight:900;letter-spacing:-.045em;line-height:1.05}.mpcrm-page-title>span{color:#94a3b8}
.mpcrm-page-description{max-width:610px;margin:.6rem 0 0;color:#64748b;font-size:.82rem;line-height:1.55}
.mpcrm-page-context{display:flex;flex-direction:column;align-items:flex-end;gap:.45rem;padding-bottom:.15rem}.mpcrm-context-badge{display:inline-flex;align-items:center;gap:.4rem;border:1px solid #dbeafe;border-radius:999px;padding:.36rem .62rem;background:#eff6ff;color:#1d4ed8;font-size:.68rem;font-weight:850}.mpcrm-context-note{color:#94a3b8;font-size:.68rem;font-weight:650}
.mpcrm-filter-card{padding:16px 18px 18px;border-color:#dbe3ec;border-radius:16px;box-shadow:0 8px 22px rgba(15,23,42,.035)}.mpcrm-filter-head{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin-bottom:15px}.mpcrm-filter-title{margin:.25rem 0 0;color:#0f172a;font-size:.95rem;font-weight:850}.mpcrm-filter-meta{display:flex;align-items:center;gap:.75rem}.mpcrm-filter-count{display:inline-flex;align-items:center;gap:.35rem;border-radius:999px;padding:.3rem .55rem;background:#f1f5f9;color:#475569;font-size:.66rem;font-weight:800}.mpcrm-filter-hint{color:#94a3b8;font-size:.67rem}.mpcrm-field-label{display:block;margin-bottom:.4rem;color:#475569;font-size:.68rem;font-weight:800}.mpcrm-input-wrap{position:relative}.mpcrm-input-wrap>i{position:absolute;left:.72rem;top:50%;z-index:2;transform:translateY(-50%);color:#94a3b8;font-size:.78rem;pointer-events:none}.mpcrm-input-wrap>.form-control{padding-left:2.1rem}.mpcrm-filter-card .form-control,.mpcrm-filter-card .form-select{height:38px;border:1px solid #dbe3ec;border-radius:9px;color:#334155;font-size:.74rem;font-weight:650;box-shadow:none}.mpcrm-filter-card .form-control::placeholder{color:#94a3b8;font-weight:500}.mpcrm-filter-card .form-control:focus,.mpcrm-filter-card .form-select:focus{border-color:#60a5fa;box-shadow:0 0 0 .18rem rgba(37,99,235,.1)}.mpcrm-apply-btn{height:38px;border:1px solid #0f172a;border-radius:9px;background:#0f172a;color:#fff;font-size:.72rem;font-weight:800}.mpcrm-apply-btn:hover{background:#1e293b;color:#fff}.mpcrm-reset-btn{display:grid;place-items:center;width:38px;height:38px;border:1px solid #dbe3ec;border-radius:9px;color:#64748b;background:#fff}.mpcrm-reset-btn:hover{border-color:#94a3b8;color:#0f172a;background:#f8fafc}
.mpcrm-executive-grid{grid-template-columns:repeat(5,minmax(0,1fr))}.mpcrm-kpi-card{min-height:100px;padding:13px 14px;gap:.6rem;border-color:#e2e8f0;border-radius:15px;box-shadow:0 4px 12px rgba(15,23,42,.025)}.mpcrm-kpi-card>div:last-child{min-width:0;flex:1}.mpcrm-kpi-card.mpcrm-kpi-danger{border-top:3px solid #dc2626}.mpcrm-kpi-danger .mpcrm-kpi-icon{background:#fef2f2;color:#dc2626}.mpcrm-kpi-icon{width:34px;height:34px;flex-basis:34px;border-radius:10px;font-size:.85rem}.mpcrm-kpi-label{font-size:.58rem;letter-spacing:.075em}.mpcrm-kpi-value{font-size:clamp(.82rem,1.05vw,1rem);line-height:1.1;letter-spacing:-.025em;white-space:nowrap;overflow:visible;text-overflow:clip}.mpcrm-kpi-note{font-size:.62rem;margin-top:4px}
.mpcrm-chart-card{padding:18px 20px 20px;border-color:#e2e8f0;border-radius:16px;box-shadow:0 8px 22px rgba(15,23,42,.03)}.mpcrm-panel-head,.mpcrm-data-card-head{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem}.mpcrm-panel-title{margin:.25rem 0 0;color:#0f172a;font-size:.98rem;font-weight:850;letter-spacing:-.015em}.mpcrm-chart-context{display:flex;align-items:center;gap:.75rem}.mpcrm-period-pill{background:#eff6ff;color:#1d4ed8}.mpcrm-chart-scope{color:#94a3b8;font-size:.68rem;font-weight:700}.mpcrm-chart-legend{padding-top:2px}.mpcrm-chart-grid{height:205px;border-radius:10px;background:repeating-linear-gradient(to bottom,transparent 0,transparent 49px,#e8eef5 50px)}.mpcrm-chart-bar{opacity:.94}.mpcrm-chart-container{min-height:252px}
.mpcrm-data-card{border-color:#e2e8f0;border-radius:16px;box-shadow:0 8px 22px rgba(15,23,42,.03)}.mpcrm-data-card-head{align-items:center;padding:17px 20px;border-bottom:1px solid #eef2f7}.mpcrm-data-card-meta{display:flex;align-items:center;gap:.65rem;color:#94a3b8;font-size:.68rem}.mpcrm-data-card-meta strong{color:#0f172a;font-size:.74rem}.mpcrm-data-divider{width:3px;height:3px;border-radius:50%;background:#cbd5e1}.mpcrm-data-card .table-responsive{border-top:0}.mpcrm-table thead th{padding:11px 14px;background:#f8fafc;color:#64748b;font-size:.61rem;letter-spacing:.1em}.mpcrm-table tbody tr{transition:background-color .15s ease}.mpcrm-table tbody tr:hover{background:#f8fbff}.mpcrm-table td{padding:13px 14px;color:#475569;font-size:.74rem}.mpcrm-table td:first-child,.mpcrm-table th:first-child{padding-left:20px}.mpcrm-table td:last-child,.mpcrm-table th:last-child{padding-right:20px}.mpcrm-order-cell{display:flex;align-items:flex-start;gap:.55rem}.mpcrm-order-marker{width:7px;height:7px;flex:0 0 7px;margin-top:.38rem;border-radius:50%;background:#60a5fa;box-shadow:0 0 0 3px #eff6ff}.mpcrm-link{font-size:.76rem;font-weight:850;letter-spacing:.01em}.mpcrm-store-name,.text-slate-strong{color:#334155;font-weight:750}.mpcrm-channel-tag{display:inline-flex;align-items:center;gap:.25rem;margin-top:.28rem;color:#94a3b8;font-size:.64rem}.mpcrm-channel-tag i{font-size:.62rem}.mpcrm-status-pill{min-width:62px;justify-content:center;font-size:.63rem;letter-spacing:.01em}.mpcrm-total-cell{color:#0f172a!important;white-space:nowrap}.mpcrm-date-cell{color:#334155;font-weight:700;font-size:.72rem}.mpcrm-row-action{display:grid;place-items:center;width:28px;height:28px;border:1px solid #e2e8f0;border-radius:8px;background:#fff;color:#64748b;text-decoration:none;transition:all .15s ease}.mpcrm-row-action:hover{border-color:#93c5fd;background:#eff6ff;color:#2563eb;transform:translate(1px,-1px)}.mpcrm-pagination{border-top:1px solid #eef2f7}.mpcrm-pagination nav{display:flex;justify-content:flex-end}.mpcrm-pagination .pagination{margin:0}
@media (max-width:1100px){.mpcrm-executive-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.mpcrm-analytics-grid{grid-template-columns:1fr 1fr}}
@media (max-width:768px){.mpcrm-module-nav{align-items:flex-start;flex-direction:column;gap:.5rem;padding:.45rem}.mpcrm-nav-links{width:100%;overflow-x:auto;flex-wrap:nowrap}.mpcrm-nav-link{flex:0 0 auto}.mpcrm-nav-context{margin-left:.15rem}.mpcrm-page-header,.mpcrm-panel-head,.mpcrm-data-card-head{align-items:flex-start;flex-direction:column}.mpcrm-page-context{align-items:flex-start}.mpcrm-filter-head{align-items:flex-start;flex-direction:column;margin-bottom:13px}.mpcrm-filter-meta{align-items:flex-start;flex-direction:column;gap:.35rem}.mpcrm-executive-grid,.mpcrm-analytics-grid{grid-template-columns:1fr 1fr}.mpcrm-analytics-grid .mpcrm-analysis-card:last-child{grid-column:auto}.mpcrm-kpi-value{font-size:clamp(.86rem,2.8vw,1rem)}.mpcrm-chart-context{width:100%;justify-content:space-between}.mpcrm-chart-legend{gap:.7rem}.mpcrm-chart-legend .mpcrm-sub{font-size:0}.mpcrm-chart-legend .mpcrm-sub i{font-size:.72rem}.mpcrm-data-card-head{gap:.6rem}.mpcrm-data-card-meta{width:100%;justify-content:flex-start}.mpcrm-table{min-width:900px}}
@media (max-width:480px){.mpcrm-executive-grid{grid-template-columns:1fr}.mpcrm-page-title{font-size:1.65rem}.mpcrm-filter-card{padding:14px}.mpcrm-chart-card{padding:16px 14px}.mpcrm-chart-grid{height:180px}.mpcrm-chart-context{align-items:flex-start;flex-direction:column;gap:.4rem}}
@media (max-width:480px){.mpcrm-segment-summary .mpcrm-value{font-size:clamp(1.05rem,6vw,1.35rem)}}
.mpcrm-segments-page{max-width:1680px;margin:0 auto}.mpcrm-segments-header{align-items:flex-start}.mpcrm-scope-form{min-width:205px}.mpcrm-scope-form .form-select{height:38px;border:1px solid #dbe3ec;border-radius:10px;color:#334155;font-size:.74rem;font-weight:700;box-shadow:0 4px 12px rgba(15,23,42,.04)}.mpcrm-segment-kpis{grid-template-columns:repeat(5,minmax(0,1fr))}.mpcrm-segment-kpis .mpcrm-kpi-value{font-size:clamp(.72rem,1.15vw,1.05rem);overflow:hidden;text-overflow:ellipsis;letter-spacing:-.04em}
.mpcrm-executive-callout{display:flex;align-items:center;gap:14px;padding:15px 18px;border:1px solid #dbeafe;border-radius:16px;background:linear-gradient(105deg,#f8fbff,#eff6ff 60%,#f8fafc);box-shadow:0 8px 24px rgba(37,99,235,.06)}.mpcrm-callout-icon{display:grid;place-items:center;width:40px;height:40px;flex:0 0 40px;border-radius:12px;background:#dbeafe;color:#2563eb;font-size:1.1rem}.mpcrm-callout-kicker{color:#2563eb;font-size:.61rem;font-weight:850;letter-spacing:.1em;text-transform:uppercase}.mpcrm-callout-title{margin-top:2px;color:#0f172a;font-size:.92rem;font-weight:850}.mpcrm-callout-copy{margin-top:3px;color:#64748b;font-size:.72rem}.mpcrm-callout-metric{min-width:165px;padding-left:18px;border-left:1px solid #bfdbfe}.mpcrm-callout-metric span,.mpcrm-callout-metric small{display:block;color:#64748b;font-size:.63rem}.mpcrm-callout-metric strong{display:block;margin:3px 0;color:#0f172a;font-size:1rem}
.mpcrm-enterprise-card{padding:18px 20px;background:#fff;border:1px solid #e2e8f0;border-radius:16px;box-shadow:0 8px 22px rgba(15,23,42,.03)}.mpcrm-enterprise-head{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem;margin-bottom:16px}.mpcrm-enterprise-title{margin:4px 0 0;color:#0f172a;font-size:1rem;font-weight:850;letter-spacing:-.02em}.mpcrm-enterprise-subtitle{margin:4px 0 0;color:#94a3b8;font-size:.68rem}.mpcrm-card-badge{display:inline-flex;align-items:center;white-space:nowrap;border-radius:999px;padding:.32rem .55rem;background:#f1f5f9;color:#64748b;font-size:.61rem;font-weight:850}.mpcrm-section-kicker{font-size:.6rem;letter-spacing:.1em}.mpcrm-section-kicker i{color:#2563eb;font-size:.75rem}.mpcrm-segment-matrix{display:grid;gap:7px}.mpcrm-segment-row{display:flex;align-items:center;gap:10px;min-width:0;padding:10px 8px;border:1px solid transparent;border-radius:12px;color:inherit;text-decoration:none;transition:background .15s,border-color .15s,transform .15s}.mpcrm-segment-row:hover{border-color:#e2e8f0;background:#f8fbff;color:inherit;transform:translateX(2px)}.mpcrm-segment-icon{display:grid;place-items:center;width:32px;height:32px;flex:0 0 32px;border-radius:10px;background:var(--segment-bg);color:var(--segment-color);font-size:.82rem}.mpcrm-segment-main{min-width:0;flex:1}.mpcrm-segment-row-head{display:flex;justify-content:space-between;gap:.5rem;color:#334155;font-size:.72rem}.mpcrm-segment-row-head span{color:#94a3b8;font-size:.62rem}.mpcrm-segment-track{height:6px;margin:6px 0 5px;overflow:hidden;border-radius:99px;background:#eef2f7}.mpcrm-segment-track span{display:block;height:100%;min-width:4px;border-radius:inherit;background:var(--segment-color)}.mpcrm-segment-row-foot{display:flex;justify-content:space-between;gap:.7rem;color:#94a3b8;font-size:.61rem}.mpcrm-segment-row-foot span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.mpcrm-segment-row-foot b{color:var(--segment-color);white-space:nowrap}.mpcrm-segment-total{min-width:112px;text-align:right}.mpcrm-segment-total strong{display:block;color:#0f172a;font-size:1rem;line-height:1}.mpcrm-segment-total span{display:block;color:#94a3b8;font-size:.58rem}.mpcrm-segment-total small{display:block;margin-top:4px;color:#64748b;font-size:.61rem;font-weight:750}.mpcrm-segment-arrow{color:#cbd5e1;font-size:.7rem}
.mpcrm-recency-list{display:grid;gap:16px;padding:3px 0 14px}.mpcrm-recency-head,.mpcrm-recency-meta{display:flex;align-items:center;justify-content:space-between;gap:.5rem}.mpcrm-recency-head{color:#475569;font-size:.7rem;font-weight:750}.mpcrm-recency-head span{display:flex;align-items:center;gap:6px}.mpcrm-recency-head i{width:8px;height:8px;border-radius:50%}.mpcrm-recency-head b{color:#0f172a}.mpcrm-recency-track{height:8px;margin-top:7px;overflow:hidden;border-radius:99px;background:#eef2f7}.mpcrm-recency-track span{display:block;height:100%;min-width:3px;border-radius:inherit}.mpcrm-recency-meta{margin-top:4px;color:#94a3b8;font-size:.6rem}.mpcrm-panel-note{padding-top:12px;border-top:1px solid #eef2f7;color:#94a3b8;font-size:.64rem;line-height:1.45}.mpcrm-value-tier-list{display:grid;gap:15px;margin:2px 0 17px}.mpcrm-tier-row{display:flex;align-items:center;gap:9px}.mpcrm-tier-dot{width:9px;height:9px;flex:0 0 9px;border-radius:50%}.mpcrm-tier-head{display:flex;justify-content:space-between;gap:.6rem;color:#334155;font-size:.7rem}.mpcrm-tier-head span{color:#0f172a;font-weight:850}.mpcrm-tier-range{margin-top:3px;color:#94a3b8;font-size:.61rem}.mpcrm-tier-row>b{min-width:105px;color:#475569;font-size:.66rem;text-align:right}
.mpcrm-insight-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.mpcrm-insight-card{display:flex;align-items:flex-start;gap:9px;min-width:0;padding:11px;border:1px solid #e2e8f0;border-radius:12px;color:inherit;text-decoration:none;transition:transform .15s,box-shadow .15s}.mpcrm-insight-card:hover{color:inherit;transform:translateY(-2px);box-shadow:0 8px 16px rgba(15,23,42,.07)}.mpcrm-insight-icon{display:grid;place-items:center;width:28px;height:28px;flex:0 0 28px;border-radius:9px;font-size:.76rem}.mpcrm-insight-body{min-width:0}.mpcrm-insight-label{overflow:hidden;color:#475569;font-size:.61rem;font-weight:800;text-overflow:ellipsis;white-space:nowrap}.mpcrm-insight-body>strong{display:block;margin:3px 0;color:#0f172a;font-size:.88rem}.mpcrm-insight-body p{min-height:30px;margin:0;color:#94a3b8;font-size:.61rem;line-height:1.4}.mpcrm-insight-body>span{display:block;margin-top:8px;color:#2563eb;font-size:.61rem;font-weight:800}.mpcrm-insight-orange .mpcrm-insight-icon{background:#fff7ed;color:#ea580c}.mpcrm-insight-green .mpcrm-insight-icon{background:#f0fdf4;color:#16a34a}.mpcrm-insight-blue .mpcrm-insight-icon{background:#eff6ff;color:#2563eb}.mpcrm-outline-action{display:inline-flex;align-items:center;border:1px solid #bfdbfe;border-radius:9px;padding:.42rem .65rem;background:#eff6ff;color:#1d4ed8;font-size:.65rem;font-weight:800;text-decoration:none}.mpcrm-outline-action:hover{background:#dbeafe;color:#1e40af}.mpcrm-action-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.mpcrm-action-card{display:block;padding:13px 14px;border:1px solid #e2e8f0;border-left:3px solid var(--segment-color);border-radius:11px;background:linear-gradient(105deg,#fff,var(--segment-bg));color:inherit;text-decoration:none;transition:transform .15s,box-shadow .15s}.mpcrm-action-card:hover{color:inherit;transform:translateY(-2px);box-shadow:0 8px 18px rgba(15,23,42,.07)}.mpcrm-action-card-top{display:flex;align-items:center;gap:6px;color:var(--segment-color);font-size:.66rem;font-weight:850}.mpcrm-action-card-top i{margin-left:auto}.mpcrm-priority-dot{width:7px;height:7px;border-radius:50%;background:var(--segment-color)}.mpcrm-action-card>strong{display:block;margin-top:11px;color:#0f172a;font-size:1.05rem}.mpcrm-action-revenue{margin-top:2px;color:#475569;font-size:.64rem;font-weight:750}.mpcrm-action-copy{margin-top:10px;color:#94a3b8;font-size:.64rem;line-height:1.4}
@media (max-width:1100px){.mpcrm-segment-kpis{grid-template-columns:repeat(3,minmax(0,1fr))}.mpcrm-insight-grid{grid-template-columns:1fr}.mpcrm-insight-body p{min-height:0}}
@media (max-width:768px){.mpcrm-segments-header{gap:1rem}.mpcrm-scope-form{width:100%}.mpcrm-executive-callout{align-items:flex-start;flex-wrap:wrap}.mpcrm-callout-metric{width:100%;padding:10px 0 0;border-top:1px solid #bfdbfe;border-left:0}.mpcrm-segment-total{min-width:80px}.mpcrm-segment-row-foot span{display:none}.mpcrm-action-grid{grid-template-columns:1fr}.mpcrm-outline-action{width:100%;justify-content:center}}
@media (max-width:480px){.mpcrm-segment-kpis{grid-template-columns:1fr 1fr}.mpcrm-enterprise-card{padding:15px 13px}.mpcrm-enterprise-head{gap:.6rem}.mpcrm-enterprise-head .mpcrm-card-badge{font-size:.55rem}.mpcrm-segment-row{gap:6px;padding:8px 3px}.mpcrm-segment-icon{width:27px;height:27px;flex-basis:27px}.mpcrm-segment-total{min-width:68px}.mpcrm-segment-total small{font-size:.53rem}.mpcrm-segment-arrow{display:none}}
</style>
