<div class="an-enterprise-grid an-tab-pane is-hidden" data-an-pane="products">
    <section class="an-enterprise-card an-product-portfolio-card"><div class="an-enterprise-head"><div><div class="an-section-kicker"><span class="an-section-kicker-dot"></span>Portfolio health</div><div class="an-enterprise-title">Kesehatan portofolio produk</div><div class="an-enterprise-sub">Ringkasan top 100 produk berdasarkan gross sales eligible pada periode terpilih.</div></div><span class="an-product-scope-pill"><i class="bi bi-shield-check"></i> Financial-ready</span></div><div class="an-enterprise-body"><div class="an-pulse-grid" id="anProductPulse"><div class="an-empty">Menunggu tab Produk dibuka…</div></div><div class="an-product-reading" id="anProductReading"><i class="bi bi-info-circle"></i><span>Gunakan profit operasional untuk melihat nilai setelah HPP dan alokasi iklan.</span></div></div></section>
    <section class="an-enterprise-card"><div class="an-enterprise-head"><div><div class="an-section-kicker"><span class="an-section-kicker-dot"></span>Decision support</div><div class="an-enterprise-title">Prioritas tindakan</div><div class="an-enterprise-sub">Sinyal yang membantu tim menentukan produk mana yang dipertahankan, diperbaiki, atau ditinjau.</div></div></div><div class="an-enterprise-body"><div class="an-alerts" id="anProductFocus"><div class="an-empty">Menunggu data produk…</div></div></div></section>
</div>

<div class="an-grid-secondary an-tab-pane is-hidden" data-an-pane="products">
    <section class="an-card"><div class="an-card-head"><div><div class="an-section-kicker"><span class="an-section-kicker-dot"></span>Product ledger</div><div class="an-card-title">Kinerja produk</div><div class="an-card-sub">Klik nama produk untuk membuka katalog. Nilai iklan dialokasikan proporsional terhadap gross sales agar profit operasional bisa dibandingkan antarproduk.</div></div><div class="an-product-toolbar"><span class="an-product-result-count" id="anProductResultCount">—</span><input id="anProductSearch" type="search" placeholder="Cari produk / SKU…"><select id="anProductHealth"><option value="all">Semua status</option><option value="healthy">Profit sehat</option><option value="negative">Profit negatif</option><option value="thin_margin">Margin tipis &lt; 10%</option><option value="missing_hpp">HPP belum lengkap</option></select><select id="anProductSort"><option value="gross_sales">Urutkan: Gross sales</option><option value="operating_profit">Urutkan: Profit operasional</option><option value="margin_pct">Urutkan: Margin operasional</option><option value="qty">Urutkan: Qty</option></select></div></div><div class="an-card-body"><div class="an-product-table-note"><span><i class="bi bi-lightbulb"></i> Fokuskan review pada status merah dan amber.</span><span><i class="bi bi-arrow-left-right"></i> Geser tabel horizontal untuk metrik lengkap.</span></div><div class="an-table-wrap"><table class="an-table an-product-table"><thead><tr><th>#</th><th>Produk</th><th>Qty</th><th>Gross sales</th><th>Payout bersih</th><th>HPP</th><th>Iklan incl. PPN</th><th>Profit setelah HPP</th><th>Profit operasional</th><th>Status</th></tr></thead><tbody id="bestProductBody"><tr><td colspan="10"><div class="an-empty">Buka tab Produk untuk memuat detail.</div></td></tr></tbody></table></div></div></section>
    <section class="an-card"><div class="an-card-head"><div><div class="an-section-kicker"><span class="an-section-kicker-dot"></span>Exception review</div><div class="an-card-title">Produk perlu perhatian</div><div class="an-card-sub">Urut dari profit operasional terendah.</div></div></div><div class="an-card-body"><div class="an-list" id="worstProductBody"><div class="an-empty">Memuat…</div></div></div></section>
</div>
