<section class="an-enterprise-card an-tab-pane is-hidden" data-an-pane="stores">
    <div class="an-enterprise-head"><div><div class="an-section-kicker"><span class="an-section-kicker-dot"></span>Account performance</div><div class="an-enterprise-title">Executive pulse</div><div class="an-enterprise-sub">Efisiensi toko berbasis omzet dan profit yang sudah siap secara finansial.</div></div></div>
    <div class="an-enterprise-body"><div class="an-pulse-grid an-pulse-grid-finance" id="anFinancePulse"><div class="an-empty">Memuat…</div></div></div>
</section>

<div class="an-tab-pane is-hidden" data-an-pane="stores">
    <div class="an-kpis">
        <div class="an-kpi primary"><span class="an-kpi-label">Total Order <i id="kpiOrdersInfo" class="bi bi-info-circle an-kpi-info" tabindex="0" role="img" aria-label="Penjelasan Total Order" data-tooltip="Order aktif yang sudah dibayar; belum bayar, batal, dan return/refund dikecualikan"></i></span><strong class="an-kpi-value" id="kpiOrders">—</strong><span class="an-kpi-note" id="kpiOrdersNote"><span title="Sudah cair"><i class="bi bi-check-circle-fill" aria-hidden="true"></i> —</span> · <span title="Belum cair"><i class="bi bi-clock-history" aria-hidden="true"></i> —</span></span></div>
        <div class="an-kpi kpi-cancelled"><span class="an-kpi-label">Dibatalkan <i id="kpiCancelledInfo" class="bi bi-info-circle an-kpi-info" tabindex="0" role="img" aria-label="Penjelasan order dibatalkan" data-tooltip="Order batal dipisahkan dan tidak masuk omzet maupun estimasi profit"></i></span><strong class="an-kpi-value" id="kpiCancelled">—</strong><span class="an-kpi-note" id="kpiCancelledNote"><span title="Nilai order batal"><i class="bi bi-x-circle" aria-hidden="true"></i> —</span> · tidak masuk omzet</span></div>
        <div class="an-kpi"><span class="an-kpi-label">Produk Terjual <i id="kpiProductsSoldInfo" class="bi bi-info-circle an-kpi-info" tabindex="0" role="img" aria-label="Penjelasan Produk Terjual" data-tooltip="Total unit · cair · pending · refund"></i></span><strong class="an-kpi-value" id="kpiProductsSold">—</strong><span class="an-kpi-note" id="kpiProductsSoldNote"><span title="Produk sudah cair"><i class="bi bi-check-circle-fill" aria-hidden="true"></i> —</span> · <span title="Produk pending"><i class="bi bi-clock-history" aria-hidden="true"></i> —</span> · <span title="Produk refund"><i class="bi bi-arrow-counterclockwise" aria-hidden="true"></i> —</span></span></div>
        <div class="an-kpi"><span class="an-kpi-label">Omzet Eligible / Gross Sales <i id="kpiRevenueInfo" class="bi bi-info-circle an-kpi-info" tabindex="0" role="img" aria-label="Penjelasan Omzet Eligible atau Gross Sales" data-tooltip="Omzet dari order yang sudah dibayar; belum bayar, batal, dan return/refund dikecualikan"></i></span><strong class="an-kpi-value" id="kpiRevenue">—</strong><span class="an-kpi-note" id="kpiRevenueNote"><span title="Sudah cair"><i class="bi bi-check-circle-fill" aria-hidden="true"></i> —</span> · <span title="Estimasi belum cair"><i class="bi bi-clock-history" aria-hidden="true"></i> —</span> · <span title="Belum bayar/batal/refund dikecualikan"><i class="bi bi-shield-check" aria-hidden="true"></i> belum bayar/batal/refund dikecualikan</span></span></div>
        <div class="an-kpi"><span class="an-kpi-label">Prakiraan Admin Fee <i id="kpiAdminFeeInfo" class="bi bi-info-circle an-kpi-info" tabindex="0" role="img" aria-label="Penjelasan Prakiraan Admin Fee" data-tooltip="Omzet × rate fee actual · komposisi fee"></i></span><strong class="an-kpi-value" id="kpiAdminFee">—</strong><span class="an-kpi-note" id="kpiAdminFeeNote">komposisi fee actual</span></div>
        <div class="an-kpi"><span class="an-kpi-label">Prakiraan Cair / Net sales <i id="kpiEstimatedCashInfo" class="bi bi-info-circle an-kpi-info" tabindex="0" role="img" aria-label="Penjelasan Prakiraan Cair atau Net sales" data-tooltip="Omzet − admin fee · net cair + estimasi"></i></span><strong class="an-kpi-value" id="kpiEstimatedCash">—</strong><span class="an-kpi-note" id="kpiEstimatedCashNote"><span title="Net sudah cair"><i class="bi bi-check-circle-fill" aria-hidden="true"></i> —</span> · <span title="Estimasi net belum cair"><i class="bi bi-clock-history" aria-hidden="true"></i> —</span> · <span title="Return/refund"><i class="bi bi-arrow-counterclockwise" aria-hidden="true"></i> —</span></span></div>
        <div class="an-kpi"><span class="an-kpi-label">Total HPP / COGS <i id="kpiHppInfo" class="bi bi-info-circle an-kpi-info" tabindex="0" role="img" aria-label="Penjelasan Total HPP atau COGS" data-tooltip="Total HPP · cair · belum cair · return/refund"></i></span><strong class="an-kpi-value" id="kpiHpp">—</strong><span class="an-kpi-note" id="kpiHppKpiNote"><span title="HPP sudah cair"><i class="bi bi-check-circle-fill" aria-hidden="true"></i> —</span> · <span title="HPP belum cair"><i class="bi bi-clock-history" aria-hidden="true"></i> —</span> · <span title="HPP return/refund"><i class="bi bi-arrow-counterclockwise" aria-hidden="true"></i> —</span></span></div>
        <div class="an-kpi"><span class="an-kpi-label">Biaya Iklan (incl. PPN)</span><strong class="an-kpi-value" id="kpiAdCost">—</strong><span class="an-kpi-note" id="kpiAdCostNote"><span title="Biaya iklan sebelum PPN"><i class="bi bi-receipt" aria-hidden="true"></i> —</span> · <span title="PPN 11%"><i class="bi bi-percent" aria-hidden="true"></i> —</span> · <span title="Biaya per order"><i class="bi bi-bag" aria-hidden="true"></i> —</span></span></div>
        <div class="an-kpi"><span class="an-kpi-label">Omzet Cair / Net Revenue</span><strong class="an-kpi-value" id="kpiPayout">—</strong><span class="an-kpi-note" id="kpiPayoutNote"><span title="Order settlement complete"><i class="bi bi-check-circle-fill" aria-hidden="true"></i> —</span> · <span title="Payout rate"><i class="bi bi-percent" aria-hidden="true"></i> —</span></span></div>
        <div class="an-kpi kpi-refund"><span class="an-kpi-label">Refund / Return <i id="kpiRefundInfo" class="bi bi-info-circle an-kpi-info" tabindex="0" role="img" aria-label="Penjelasan refund atau return" data-tooltip="Nilai refund dipisahkan dan tidak masuk omzet maupun estimasi profit"></i></span><strong class="an-kpi-value" id="kpiRefund">—</strong><span class="an-kpi-note" id="kpiRefundNote"><span title="Jumlah order refund"><i class="bi bi-bag" aria-hidden="true"></i> —</span> · rate —</span></div>
        <div class="an-kpi"><span class="an-kpi-label">Laba Kotor / Gross Profit <i id="kpiGrossProfitInfo" class="bi bi-info-circle an-kpi-info" tabindex="0" role="img" aria-label="Penjelasan Laba Kotor atau Gross Profit" data-tooltip="Net revenue − total HPP"></i></span><strong class="an-kpi-value" id="kpiGrossProfit">—</strong><span class="an-kpi-note" id="kpiHppNote"><span title="Net revenue"><i class="bi bi-cash-stack" aria-hidden="true"></i> —</span> · <span title="Total HPP"><i class="bi bi-box-seam" aria-hidden="true"></i> —</span></span></div>
        <div class="an-kpi"><span class="an-kpi-label">Est. Laba Bersih / Est. Net Profit</span><strong class="an-kpi-value" id="kpiEstimatedProfit">—</strong><span class="an-kpi-note" id="kpiEstimatedProfitNote"><span title="Margin estimasi"><i class="bi bi-graph-up-arrow" aria-hidden="true"></i> —</span> · <span title="Net revenue − HPP − iklan"><i class="bi bi-calculator" aria-hidden="true"></i> estimasi</span></span></div>
        <div class="an-kpi"><span class="an-kpi-label">Laba Operasional / Net Operasional</span><strong class="an-kpi-value" id="kpiOperatingProfit">—</strong><span class="an-kpi-note" id="kpiOperatingProfitNote"><span title="Omzet cair"><i class="bi bi-cash-coin" aria-hidden="true"></i> —</span> · <span title="Total HPP + iklan"><i class="bi bi-dash-circle" aria-hidden="true"></i> —</span></span></div>
    </div>
</div>

<div class="an-enterprise-grid an-tab-pane is-hidden" data-an-pane="stores">
    <section class="an-enterprise-card"><div class="an-enterprise-head"><div><div class="an-section-kicker"><span class="an-section-kicker-dot"></span>Portfolio view</div><div class="an-enterprise-title">Store performance snapshot</div><div class="an-enterprise-sub">Ranking toko berdasarkan gross sales dan profit operasional terverifikasi.</div></div></div><div class="an-enterprise-body"><div class="an-pulse-grid" id="anStorePulse"><div class="an-empty">Memuat…</div></div></div></section>
    <section class="an-enterprise-card"><div class="an-enterprise-head"><div><div class="an-section-kicker"><span class="an-section-kicker-dot"></span>Cost structure</div><div class="an-enterprise-title">Cost efficiency</div><div class="an-enterprise-sub">Rasio biaya terhadap gross sales terverifikasi, bukan GMV operasional.</div></div></div><div class="an-enterprise-body"><div class="an-health-list" id="anStoreCostPulse"><div class="an-empty">Memuat…</div></div></div></section>
</div>

<div class="an-grid-secondary an-tab-pane is-hidden" data-an-pane="stores">
    <section class="an-card"><div class="an-card-head"><div><div class="an-section-kicker"><span class="an-section-kicker-dot"></span>Store ledger</div><div class="an-card-title">Performa per toko</div><div class="an-card-sub">Hanya order financial-ready: settlement complete, item valid, dan HPP tersedia.</div></div></div><div class="an-card-body"><div class="an-table-wrap"><table class="an-table"><thead><tr><th>Toko</th><th>Order eligible</th><th>Selesai</th><th>Cancel</th><th>Gross sales terverifikasi</th><th>Profit operasional</th></tr></thead><tbody id="storeBody"><tr><td colspan="6"><div class="an-empty">Memuat…</div></td></tr></tbody></table></div></div></section>
    <section class="an-card"><div class="an-card-head"><div><div class="an-card-title">Biaya marketplace</div><div class="an-card-sub">Fee estimasi mengikuti rate actual Unit economics; biaya settlement tetap tersedia untuk audit</div></div></div><div class="an-card-body"><div class="an-costs" id="costBody"><div class="an-empty">Memuat…</div></div></div></section>
</div>
