<div class="an-enterprise-grid an-tab-pane is-hidden" data-an-pane="products">
    <section class="an-enterprise-card"><div class="an-enterprise-head"><div><div class="an-section-kicker"><span class="an-section-kicker-dot"></span>Portfolio view</div><div class="an-enterprise-title">Product portfolio</div><div class="an-enterprise-sub">Top produk berdasarkan gross sales dari order financial-ready dengan HPP valid.</div></div></div><div class="an-enterprise-body"><div class="an-pulse-grid" id="anProductPulse"><div class="an-empty">Menunggu tab Produk dibuka…</div></div></div></section>
    <section class="an-enterprise-card"><div class="an-enterprise-head"><div><div class="an-section-kicker"><span class="an-section-kicker-dot"></span>Decision support</div><div class="an-enterprise-title">Product focus</div><div class="an-enterprise-sub">Prioritas berdasarkan profit setelah HPP dan alokasi biaya iklan.</div></div></div><div class="an-enterprise-body"><div class="an-alerts" id="anProductFocus"><div class="an-empty">Menunggu data produk…</div></div></div></section>
</div>

<div class="an-grid-secondary an-tab-pane is-hidden" data-an-pane="products">
    <section class="an-card"><div class="an-card-head"><div><div class="an-section-kicker"><span class="an-section-kicker-dot"></span>Product ledger</div><div class="an-card-title">Top produk financial-ready</div><div class="an-card-sub">Maksimal 100 produk, diurutkan dari gross sales. Gross sales dan payout berasal dari settlement complete; iklan dialokasikan proporsional terhadap gross sales produk.</div></div><div class="an-product-toolbar"><input id="anProductSearch" type="search" placeholder="Cari produk / SKU…"><select id="anProductSort"><option value="gross_sales">Urutkan: Gross sales</option><option value="operating_profit">Urutkan: Profit operasional</option><option value="margin_pct">Urutkan: Margin operasional</option><option value="qty">Urutkan: Qty</option></select></div></div><div class="an-card-body"><div class="an-table-wrap"><table class="an-table an-product-table"><thead><tr><th>#</th><th>Produk</th><th>Qty</th><th>Gross sales</th><th>Payout bersih</th><th>HPP</th><th>Iklan incl. PPN</th><th>Profit setelah HPP</th><th>Profit operasional</th></tr></thead><tbody id="bestProductBody"><tr><td colspan="9"><div class="an-empty">Buka tab Produk untuk memuat detail.</div></td></tr></tbody></table></div></div></section>
    <section class="an-card"><div class="an-card-head"><div><div class="an-section-kicker"><span class="an-section-kicker-dot"></span>Exception review</div><div class="an-card-title">Produk perlu perhatian</div><div class="an-card-sub">Urut dari profit operasional terendah.</div></div></div><div class="an-card-body"><div class="an-list" id="worstProductBody"><div class="an-empty">Memuat…</div></div></div></section>
</div>
